 --- #YAML:1.0
 name: Lyrics-Fetcher-AZLyrics
 abstract: Get song lyrics from www.azlyrics.com
 version: 0.03
 author:
   - David Precious <davidp@preshweb.co.uk>
 license: perl
 distribution_type: module
 requires:
   LWP::UserAgent: 0
   HTML::TokeParser: 0
   perl: 5.005
 build_requires:
   Test::More: 0
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 generated_by: hand
